# -*- coding: utf-8 -*-
"""Assignment2_If-else.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19032_44B_EhDCmljNeQN08NIwNsEqubs
"""

# Q1: Comparing Rectangle Areas
print("Q1: Comparing Rectangle Areas")
length1 = float(input("Enter length of first rectangle: "))
width1 = float(input("Enter width of first rectangle: "))
length2 = float(input("Enter length of second rectangle: "))
width2 = float(input("Enter width of second rectangle: "))

area1 = length1 * width1
area2 = length2 * width2

print(f"Area of first rectangle: {area1}")
print(f"Area of second rectangle: {area2}")

if area1 > area2:
    print("First rectangle has a larger area.")
elif area2 > area1:
    print("Second rectangle has a larger area.")
else:
    print("Both rectangles have the same area.")

# Q2: Even/Odd and Positive/Negative
print("Q2: Even/Odd and Positive/Negative")
num = int(input("Enter a number: "))

if num % 2 == 0:
    print("The number is Even")
else:
    print("The number is Odd")

if num > 0:
    print("The number is Positive")
elif num < 0:
    print("The number is Negative")
else:
    print("The number is Zero")

# Q3: Tax Calculation by Income Slab
print("Q3: Tax Calculation by Income Slab")
salary = float(input("Enter your salary: "))

if salary > 100000:
    tax_rate = 0.20
elif salary > 50000:
    tax_rate = 0.10
else:
    tax_rate = 0.05

tax = salary * tax_rate
net_salary = salary - tax

print(f"Salary before tax: {salary}")
print(f"Tax deducted: {tax}")
print(f"Salary after tax: {net_salary}")

# Q4: Shipping Cost Calculation
print("Q4: Shipping Cost Calculation")
weight = float(input("Enter parcel weight (kg): "))

if weight > 20:
    cost_per_kg = 15
elif weight >= 10:
    cost_per_kg = 10
else:
    cost_per_kg = 5

total_cost = weight * cost_per_kg
print(f"Shipping cost: {total_cost}")

# Q5: Smallest and Greatest of Three Numbers
print("Q5: Smallest and Greatest of Three Numbers")
a = float(input("Enter first number: "))
b = float(input("Enter second number: "))
c = float(input("Enter third number: "))

smallest = min(a, b, c)
greatest = max(a, b, c)

print(f"Smallest number: {smallest}")
print(f"Greatest number: {greatest}")